### ISSUE TITLE
[question] Why -O0?

### ISSUE THREAD

**Issue by AndrewJDR** [jacobmarble/cloudflare-workers-wasm-argon2-example#1]
Hello, thanks for putting together this example. Do you happen to understand why -O0 is needed? I actually tried -O1, -O2 and -Os and noted that they don't work, but i'm not entirely sure why that is and was wondering if you happened to know. Thanks again!

**Comment by jacobmarble** [comment]
@AndrewJDR any sort of optimization seems to prune any unused exported functions. Does #2 help?

**Comment by AndrewJDR** [comment]
@jacobmarble Thanks. I gave that a try but no luck (same problem). At some point i'll try to take a closer look at this and will post back here if I find anything. I'll need to get more familiar with the tools for identifying missing references in wasm files.

**Comment by jacobmarble** [comment]
I had to fix this issue in my actual use of this example, but I don't remember all the details, and TBH, I can't reproduce the issue here now, so #2 is just a stab in the dark. I'll try again when I have a few minutes.

**Comment by jacobmarble** [comment]
I just tested #2 with `npx wrangler dev`, and it does work. If I drop the `,_malloc,_free` change from #2 (but keep the `-O3` change) then the error emitted is `wasmModule._malloc is not a function`.

I'll merge this; at least it is an incremental improvement.
